# Default persona overrides for developer workstations
persona: dev
observability_install_node_exporter: false
observability_install_promtail: false
observability_install_osquery: false
observability_install_fleetctl: false
observability_install_netdata: false
activitywatch_install: false
