---
mani_install: true
mani_repo_url: "{{ lookup('env','MANI_REPO_URL') | default('git@github.com:Beta-Techno/atlas.git', true) }}"
mani_repo_path: "{{ lookup('env','MANI_REPO_PATH') | default(ansible_env.HOME + '/code/infra/atlas', true) }}"
mani_bin_path: "{{ lookup('env','MANI_BIN') | default('/usr/local/bin/mani', true) }}"
mani_sync_tags_raw: "{{ lookup('env','MANI_SYNC_TAGS') | default('infra', true) }}"
mani_run_commands_raw: "{{ lookup('env','MANI_RUN_COMMANDS') | default('', true) }}"
mani_version: "{{ lookup('env','MANI_VERSION') | default('v0.31.2', true) }}"
mani_arch_map:
  amd64: amd64
  arm64: arm64
mani_version_number: "{{ mani_version | regex_replace('^v', '') }}"
mani_sync_tags: >-
  {{ mani_sync_tags_raw | regex_replace('\s+', '') | split(',') | reject('equalto', '') | list }}
mani_run_commands: >-
  {{ mani_run_commands_raw | regex_replace('\s+', '') | split(',') | reject('equalto', '') | list }}
mani_manifests: []
mani_env:
  SOPS_AGE_KEY_FILE: "{{ lockbox_age_key_file }}"
  LOCKCTL_BIN: "{{ lockbox_lockctl_path }}"
  LOCKBOX_ENV: "{{ mani_lockbox_env | default(persona, true) }}"
  LOCKBOX_STACK: "{{ mani_lockbox_stack | default('bootstrap', true) }}"
  LOCKBOX_OUT: "{{ mani_lockbox_out | default(anvil_repo_path, true) }}"
mani_lockbox_env: "{{ persona }}"
mani_lockbox_stack: bootstrap
mani_lockbox_out: "{{ anvil_repo_path }}"
mani_workspace_dirs:
  - "{{ ansible_env.HOME }}/code/infra"
  - "{{ ansible_env.HOME }}/code/web"
  - "{{ ansible_env.HOME }}/code/web/static"
  - "{{ ansible_env.HOME }}/code/web/react"
  - "{{ ansible_env.HOME }}/code/web/nextjs"
  - "{{ ansible_env.HOME }}/code/web/solid"
  - "{{ ansible_env.HOME }}/code/web/svelte"
  - "{{ ansible_env.HOME }}/code/web/mono"
  - "{{ ansible_env.HOME }}/code/web/npm"
  - "{{ ansible_env.HOME }}/code/service"
  - "{{ ansible_env.HOME }}/code/service/go"
  - "{{ ansible_env.HOME }}/code/service/typescript"
